"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { driveFileName } from "@/lib/slugify";
import { guessCategoryId } from "@/lib/category-match";
import { uploadDriveFileInChunks } from "@/lib/upload-client";
import { ReadingDashboard } from "@/components/ReadingDashboard";
import { CorrectionDashboard } from "@/components/CorrectionDashboard";
import type { Book,BookMetadataResult,BookRequest,Category,Profile } from "@/lib/types";

type Props={initialBooks:Book[];initialCoverlessBooks:Book[];initialCorrectionBooks:Book[];initialCorrectionCount:number;initialEditBook:Book|null;initialCategories:Category[];initialProfiles:Profile[];initialRequests:BookRequest[]};
type Tab="editar"|"capas"|"corrigir"|"leitura"|"pedidos"|"categorias"|"usuarios"|"drive";
type Draft={title:string;author:string;description:string;language:string;year:string;pages:string;categoryId:string;coverUrl:string;published:boolean};
type LocalMetadata={title?:string;author?:string;description?:string;language?:string;year?:number;pages?:number;subjects?:string[];coverFile?:File};
type InviteResult={code:string;link:string;expiresAt:string;planType:"monthly"|"lifetime"};
const emptyDraft:Draft={title:"",author:"",description:"",language:"pt",year:"",pages:"",categoryId:"",coverUrl:"",published:true};

function languageName(value?:string|null){return ({pt:"Português",en:"Inglês",es:"Espanhol",fr:"Francês",it:"Italiano",de:"Alemão"} as Record<string,string>)[value||""]||value||"Não informado";}
function date(value:string){return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short"}).format(new Date(value));}
function normText(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();}
function compactIsbn(value:string){return value.replace(/[^0-9X]/gi,"").toUpperCase();}
function completeIsbn(value:string){return /^(?:\d{9}[\dX]|\d{13})$/.test(compactIsbn(value));}
function partialIsbn(value:string){return /^[\dX\s-]+$/i.test(value.trim())&&!completeIsbn(value);}
function cleanMarkup(value?:string|null){if(!value)return "";const div=document.createElement("div");div.innerHTML=value;return (div.textContent||div.innerText||"").replace(/\s+/g," ").trim();}
function normalizeLanguage(value?:string|null){if(!value)return undefined;const x=value.trim().toLowerCase().replace(/_/g,"-");const map:Record<string,string>={por:"pt",ptbr:"pt","pt-br":"pt",eng:"en",spa:"es",fra:"fr",fre:"fr",ita:"it",deu:"de",ger:"de"};return map[x.replace(/-/g,"")]||map[x]||x.split("-")[0];}
function yearFrom(value?:string|null){const match=value?.match(/\b(1[5-9]\d{2}|20\d{2}|21\d{2})\b/);return match?Number(match[1]):undefined;}
function xmlValues(doc:Document,name:string){return Array.from(doc.getElementsByTagNameNS("*",name)).map(node=>(node.textContent||"").trim()).filter(Boolean);}
function resolveZipPath(baseFile:string,href:string){const base=baseFile.includes("/")?baseFile.slice(0,baseFile.lastIndexOf("/")+1):"";const parts=(base+href).split("/");const out:string[]=[];for(const part of parts){if(!part||part===".")continue;if(part==="..")out.pop();else out.push(part);}return decodeURIComponent(out.join("/"));}

async function readEpubMetadata(file:File):Promise<LocalMetadata>{
  const JSZip=(await import("jszip")).default;const zip=await JSZip.loadAsync(await file.arrayBuffer());
  const container=await zip.file("META-INF/container.xml")?.async("text");if(!container)return {};
  const parser=new DOMParser();const containerDoc=parser.parseFromString(container,"application/xml");
  const root=containerDoc.getElementsByTagNameNS("*","rootfile")[0];const opfPath=root?.getAttribute("full-path")||"";if(!opfPath)return {};
  const opfText=await zip.file(opfPath)?.async("text");if(!opfText)return {};
  const opf=parser.parseFromString(opfText,"application/xml");
  const titles=xmlValues(opf,"title"),creators=xmlValues(opf,"creator"),languages=xmlValues(opf,"language"),dates=xmlValues(opf,"date"),descriptions=xmlValues(opf,"description"),subjects=xmlValues(opf,"subject");
  let coverFile:File|undefined;
  try{
    const items=Array.from(opf.getElementsByTagNameNS("*","item"));let coverItem=items.find(item=>(item.getAttribute("properties")||"").split(/\s+/).includes("cover-image"));
    if(!coverItem){const metas=Array.from(opf.getElementsByTagNameNS("*","meta"));const coverId=metas.find(meta=>(meta.getAttribute("name")||"").toLowerCase()==="cover")?.getAttribute("content");if(coverId)coverItem=items.find(item=>item.getAttribute("id")===coverId);}
    const href=coverItem?.getAttribute("href");if(href){const entry=zip.file(resolveZipPath(opfPath,href));if(entry){const mime=coverItem?.getAttribute("media-type")||"image/jpeg";const blob=await entry.async("blob");const ext=mime.includes("png")?"png":mime.includes("webp")?"webp":"jpg";coverFile=new File([blob],`capa-extraida.${ext}`,{type:mime});}}
  }catch{}
  return {title:titles[0],author:creators.join(", ")||undefined,description:cleanMarkup(descriptions[0]),language:normalizeLanguage(languages[0]),year:yearFrom(dates[0]),subjects,coverFile};
}

async function readPdfMetadata(file:File):Promise<LocalMetadata>{
  const {PDFDocument}=await import("pdf-lib");const pdf=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:true});
  let year: number|undefined;try{year=yearFrom(pdf.getCreationDate()?.toISOString());}catch{}
  return {title:pdf.getTitle()?.trim()||undefined,author:pdf.getAuthor()?.trim()||undefined,description:pdf.getSubject()?.trim()||undefined,year,pages:pdf.getPageCount()||undefined};
}

export function AdminDashboard({initialBooks,initialCoverlessBooks,initialCorrectionBooks,initialCorrectionCount,initialEditBook,initialCategories,initialProfiles,initialRequests}:Props){
  const [tab,setTab]=useState<Tab>("editar");
  const [books,setBooks]=useState(initialEditBook&&!initialBooks.some(book=>book.id===initialEditBook.id)?[initialEditBook,...initialBooks]:initialBooks);const [coverlessBooks,setCoverlessBooks]=useState(initialCoverlessBooks);const [categories,setCategories]=useState(initialCategories);const [profiles,setProfiles]=useState(initialProfiles);const [requests,setRequests]=useState(initialRequests);
  const [draft,setDraft]=useState<Draft>(initialEditBook?{title:initialEditBook.title,author:initialEditBook.author,description:initialEditBook.description||"",language:initialEditBook.language||"pt",year:initialEditBook.year?String(initialEditBook.year):"",pages:initialEditBook.pages?String(initialEditBook.pages):"",categoryId:initialEditBook.category_id||"",coverUrl:initialEditBook.cover_url||"",published:initialEditBook.published}:emptyDraft);const [editing,setEditing]=useState<Book|null>(initialEditBook);const [requestId,setRequestId]=useState<string|null>(null);
  const [epubFile,setEpubFile]=useState<File|null>(null);const [pdfFile,setPdfFile]=useState<File|null>(null);const [coverFile,setCoverFile]=useState<File|null>(null);
  const [suggestions,setSuggestions]=useState<BookMetadataResult[]>([]);const [searching,setSearching]=useState(false);const [metadataError,setMetadataError]=useState("");const [selected,setSelected]=useState<BookMetadataResult|null>(null);
  const [bookSearch,setBookSearch]=useState("");const [bookSearchResults,setBookSearchResults]=useState<Book[]>([]);const [bookSearchBusy,setBookSearchBusy]=useState(false);const [bookSearchError,setBookSearchError]=useState("");const [coverSearch,setCoverSearch]=useState("");const [coverSearchResults,setCoverSearchResults]=useState<Book[]>([]);const [coverSearchBusy,setCoverSearchBusy]=useState(false);const [coverEditingId,setCoverEditingId]=useState<string|null>(null);const [coverDraftUrl,setCoverDraftUrl]=useState("");const [coverImage,setCoverImage]=useState<File|null>(null);const [coverBusyId,setCoverBusyId]=useState<string|null>(null);const [fileMetadataNote,setFileMetadataNote]=useState("");const [telegramBusyId,setTelegramBusyId]=useState<string|null>(null);
  const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [progress,setProgress]=useState(0);const [drive,setDrive]=useState<{connected:boolean;accountEmail?:string|null}>({connected:false});
  const [invitePlan,setInvitePlan]=useState<"monthly"|"lifetime">("lifetime");const [invite,setInvite]=useState<InviteResult|null>(null);const [correctionCount,setCorrectionCount]=useState(initialCorrectionCount);
  const pendingRequests=requests.filter(item=>item.status==="pending");const completedRequests=requests.filter(item=>item.status!=="pending");
  const suggestedCategory=selected?guessCategoryId(categories,selected.categories||[],selected.title,selected.description||""):null;
  const normalizedBookSearch=normText(bookSearch);const bookSearchReady=normalizedBookSearch.length>=4;
  const shownBooks=bookSearchReady?bookSearchResults:books.slice(0,8);
  const normalizedCoverSearch=normText(coverSearch);const coverSearchReady=normalizedCoverSearch.length>=4;
  const shownCoverlessBooks=coverSearchReady?coverSearchResults:coverlessBooks.slice(0,12);

  async function refreshDrive(){try{const response=await fetch("/api/drive/status",{cache:"no-store"});const data=await response.json();if(response.ok)setDrive(data);}catch{}}
  useEffect(()=>{void refreshDrive();},[]);
  useEffect(()=>{
    const query=bookSearch.trim();if(normText(query).length<4){setBookSearchResults([]);setBookSearchBusy(false);setBookSearchError("");return;}
    const controller=new AbortController();const timer=setTimeout(async()=>{setBookSearchBusy(true);setBookSearchError("");try{const response=await fetch(`/api/admin/book-search?q=${encodeURIComponent(query)}`,{signal:controller.signal,cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"A pesquisa falhou.");setBookSearchResults((data.books||[]) as Book[]);}catch(error){if(!controller.signal.aborted){setBookSearchResults([]);setBookSearchError(error instanceof Error?error.message:"A pesquisa falhou.");}}finally{if(!controller.signal.aborted)setBookSearchBusy(false);}},220);
    return()=>{clearTimeout(timer);controller.abort();};
  },[bookSearch]);
  useEffect(()=>{
    const query=coverSearch.trim();if(normText(query).length<4){setCoverSearchResults([]);setCoverSearchBusy(false);return;}
    const controller=new AbortController();const timer=setTimeout(async()=>{setCoverSearchBusy(true);try{const response=await fetch(`/api/admin/book-search?q=${encodeURIComponent(query)}`,{signal:controller.signal,cache:"no-store"});const data=await response.json();if(response.ok)setCoverSearchResults((data.books||[]) as Book[]);}catch{}finally{if(!controller.signal.aborted)setCoverSearchBusy(false);}},220);
    return()=>{clearTimeout(timer);controller.abort();};
  },[coverSearch]);
  useEffect(()=>{
    if(editing||selected||draft.title.trim().length<2||partialIsbn(draft.title)){setSuggestions([]);setMetadataError("");return;}
    const controller=new AbortController();const timer=setTimeout(async()=>{setSearching(true);setMetadataError("");try{const response=await fetch(`/api/book-metadata?title=${encodeURIComponent(draft.title)}`,{signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error||"A busca não respondeu.");const results=(data.results||[]) as BookMetadataResult[];if(completeIsbn(draft.title)&&results[0])chooseMetadata(results[0]);else{setSuggestions(results);if(!results.length)setMetadataError("Nenhum resultado encontrado. Confira o ISBN ou continue preenchendo manualmente.");}}catch(error){if(!controller.signal.aborted)setMetadataError(error instanceof Error?error.message:"A busca falhou. Tente novamente.");}finally{if(!controller.signal.aborted)setSearching(false);}},completeIsbn(draft.title)?120:650);
    return()=>{clearTimeout(timer);controller.abort();};
  },[draft.title,selected,editing]);

  function chooseMetadata(item:BookMetadataResult){setSelected(item);setSuggestions([]);setDraft(current=>({...current,title:item.title,author:item.author,description:item.description||"",language:item.language||"pt",year:item.year?String(item.year):"",pages:item.pages?String(item.pages):"",coverUrl:item.coverUrl||"",categoryId:guessCategoryId(categories,item.categories||[],item.title,item.description||"")||current.categoryId}));}
  function resetForm(){setEditing(null);setRequestId(null);setSelected(null);setSuggestions([]);setMetadataError("");setDraft(emptyDraft);setEpubFile(null);setPdfFile(null);setCoverFile(null);setFileMetadataNote("");setProgress(0);(document.getElementById("book-form") as HTMLFormElement|null)?.reset();}
  function editBook(book:Book){setEditing(book);setRequestId(null);setSelected(null);setDraft({title:book.title,author:book.author,description:book.description||"",language:book.language||"pt",year:book.year?String(book.year):"",pages:book.pages?String(book.pages):"",categoryId:book.category_id||"",coverUrl:book.cover_url||"",published:book.published});setEpubFile(null);setPdfFile(null);setCoverFile(null);setFileMetadataNote("");setTab("editar");window.scrollTo({top:0,behavior:"smooth"});}
  function useRequest(item:BookRequest){resetForm();setRequestId(item.id);setDraft({...emptyDraft,title:item.title,author:item.author,language:item.language});setTab("editar");window.scrollTo({top:0,behavior:"smooth"});}

  async function absorbFileMetadata(file:File,kind:"epub"|"pdf"){
    setFileMetadataNote(`Lendo dados do ${kind.toUpperCase()} no seu dispositivo...`);
    try{
      const meta=kind==="epub"?await readEpubMetadata(file):await readPdfMetadata(file);
      if(meta.coverFile&&!coverFile&&!draft.coverUrl.trim())setCoverFile(meta.coverFile);
      setDraft(current=>{
        const title=(!current.title.trim()||completeIsbn(current.title))&&meta.title?meta.title:current.title;const description=current.description.trim()||meta.description||"";
        const categoryId=current.categoryId||guessCategoryId(categories,meta.subjects||[],title,description)||"";
        const autoLanguage=!editing&&!selected&&current.language==="pt"&&meta.language?meta.language:current.language||meta.language||"pt";
        return {...current,title,author:current.author.trim()||meta.author||"",description,language:autoLanguage,year:current.year||String(meta.year||""),pages:current.pages||String(meta.pages||""),categoryId};
      });
      const found=[meta.title&&"título",meta.author&&"autor",meta.description&&"sinopse",meta.year&&"ano",meta.pages&&"páginas",meta.coverFile&&"capa"].filter(Boolean);
      setFileMetadataNote(found.length?`Dados lidos do ${kind.toUpperCase()}: ${found.join(", ")}. Os campos já preenchidos foram preservados.`:`O ${kind.toUpperCase()} não trouxe metadados úteis; a busca online continua disponível.`);
    }catch{setFileMetadataNote(`Não consegui ler os metadados internos deste ${kind.toUpperCase()}, mas o arquivo pode ser publicado normalmente.`);}
  }

  async function uploadFile(bookTitle:string,file:File,mimeType:string,onProgress:(value:number)=>void){
    const sessionResponse=await fetch("/api/drive/upload-url",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:bookTitle,originalFileName:file.name,mimeType,fileSize:file.size})});
    const session=await sessionResponse.json();if(!sessionResponse.ok){if(session.needsConnection)setTab("drive");throw new Error(session.error||"Falha ao preparar upload.");}
    const uploaded=await uploadDriveFileInChunks(session.uploadUrl,new File([file],file.name,{type:mimeType}),onProgress);return {id:uploaded.id,fileName:session.fileName as string};
  }

  async function publishBookOnTelegram(bookId:string,force=false){
    setTelegramBusyId(bookId);try{const response=await fetch("/api/admin/telegram/channels",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"publish_book",bookId,force})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível publicar no Telegram.");const sent=(data.results||[]).filter((item:any)=>item.status==="sent").length;const skipped=(data.results||[]).filter((item:any)=>item.status==="already-sent").length;const failed=(data.results||[]).filter((item:any)=>item.status==="failed"||item.status==="partial").length;return ` Telegram: ${sent} canal(is) enviado(s)${skipped?`, ${skipped} já estava(m) publicado(s)`:""}${failed?`, ${failed} com falha parcial`:""}.`; }finally{setTelegramBusyId(null);}
  }

  function requestAdminNotification(){if("Notification" in window&&Notification.permission==="default")void Notification.requestPermission();}
  function notifyAdmin(title:string,body:string){if("Notification" in window&&Notification.permission==="granted")new Notification(title,{body,icon:"/leituraverso-logo-dark-v2.svg"});if("vibrate" in navigator)navigator.vibrate([120,60,120]);}

  async function saveBook(_formData:FormData,publishTelegram=false){
    if(!draft.title.trim()||!draft.author.trim()){setMessage("Preencha título e autor.");return;}
    if(!editing&&(!epubFile||!pdfFile)){setMessage("Para cadastrar um livro novo, o EPUB e o PDF são obrigatórios.");return;}
    requestAdminNotification();setBusy(true);setProgress(0);setMessage("");
    try{
      let coverUrl=draft.coverUrl.trim();
      if(coverFile){const form=new FormData();form.append("file",coverFile);const response=await fetch("/api/admin/covers",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível enviar a capa.");coverUrl=data.coverUrl;}
      const epub=epubFile?await uploadFile(draft.title,epubFile,"application/epub+zip",value=>setProgress(Math.round(value*(pdfFile?0.5:1)))):null;
      const pdf=pdfFile?await uploadFile(draft.title,pdfFile,"application/pdf",value=>setProgress((epub?50:0)+Math.round(value*(epub?0.5:1)))):null;
      const body:Record<string,unknown>={id:editing?.id,title:draft.title,author:draft.author,description:draft.description,language:draft.language,year:draft.year,pages:draft.pages,categoryId:draft.categoryId,coverUrl,published:true,requestId};
      if(epub){body.driveFileId=epub.id;body.fileName=epub.fileName;body.mimeType="application/epub+zip";if(pdf){body.readingPdfDriveFileId=pdf.id;body.readingPdfFileName=pdf.fileName;}else if(editing&&editing.reading_pdf_drive_file_id){body.readingPdfDriveFileId=editing.reading_pdf_drive_file_id;body.readingPdfFileName=editing.reading_pdf_file_name;}}
      else if(pdf){if(editing&&(editing.mime_type==="application/epub+zip"||editing.file_name.toLowerCase().endsWith(".epub"))){body.readingPdfDriveFileId=pdf.id;body.readingPdfFileName=pdf.fileName;}else{body.driveFileId=pdf.id;body.fileName=pdf.fileName;body.mimeType="application/pdf";}}
      const response=await fetch("/api/admin/books",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível salvar o livro.");
      if(editing){setBooks(current=>current.map(book=>book.id===data.book.id?data.book:book));setBookSearchResults(current=>current.map(book=>book.id===data.book.id?data.book:book));setCoverSearchResults(current=>current.map(book=>book.id===data.book.id?data.book:book));if(data.book.cover_url)setCoverlessBooks(current=>current.filter(book=>book.id!==data.book.id));}else setBooks(current=>[data.book,...current]);
      if(requestId)setRequests(current=>current.map(item=>item.id===requestId?{...item,status:"published",matched_book_id:data.book.id,published_at:new Date().toISOString(),notified_at:data.notification?.notificationSent?new Date().toISOString():null}:item));
      let telegramSuffix="";
      if(publishTelegram&&data.book.published){try{telegramSuffix=await publishBookOnTelegram(data.book.id);}catch(error){telegramSuffix=` Livro salvo, mas o Telegram não foi enviado: ${error instanceof Error?error.message:"falha desconhecida"}`;}}
      const successMessage=`${editing?"Livro atualizado":"Livro publicado"} com sucesso.${data.notification?.notificationSent?" O usuário foi avisado pelo Telegram.":""}${telegramSuffix}`;setMessage(successMessage);notifyAdmin(telegramSuffix.includes("falha")?"Livro salvo; confira o Telegram":"Livro enviado",telegramSuffix.includes("falha")?`${data.book.title} entrou no site, mas houve falha no Telegram.`:`${data.book.title} foi publicado no site e enviado aos canais do Telegram.`);resetForm();
    }catch(error){const errorMessage=error instanceof Error?error.message:"Erro ao salvar livro.";setMessage(errorMessage);notifyAdmin("Falha ao enviar livro",errorMessage);}finally{setBusy(false);}
  }

  async function publishExisting(book:Book){setMessage("");try{const suffix=await publishBookOnTelegram(book.id,true);setMessage(`${book.title}:${suffix}`);}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível reenviar ao Telegram.");}}
  async function removeBook(id:string){if(!confirm("Excluir este livro do catálogo?"))return;const response=await fetch(`/api/admin/books?id=${encodeURIComponent(id)}`,{method:"DELETE"});const data=await response.json();if(response.ok){setBooks(current=>current.filter(book=>book.id!==id));setCoverlessBooks(current=>current.filter(book=>book.id!==id));setBookSearchResults(current=>current.filter(book=>book.id!==id));setCoverSearchResults(current=>current.filter(book=>book.id!==id));setMessage("Livro excluído.");}else setMessage(data.error||"Não foi possível excluir.");}
  function editCover(book:Book){setCoverEditingId(book.id);setCoverDraftUrl("");setCoverImage(null);setMessage("");}
  function cancelCoverEdit(){setCoverEditingId(null);setCoverDraftUrl("");setCoverImage(null);}
  async function saveCover(book:Book){
    if(!coverImage&&!coverDraftUrl.trim()){setMessage("Envie uma imagem ou informe a URL da capa.");return;}
    setCoverBusyId(book.id);setMessage("");
    try{
      let coverUrl=coverDraftUrl.trim();
      if(coverImage){const form=new FormData();form.append("file",coverImage);const upload=await fetch("/api/admin/covers",{method:"POST",body:form});const uploaded=await upload.json();if(!upload.ok)throw new Error(uploaded.error||"Não foi possível enviar a capa.");coverUrl=uploaded.coverUrl;}
      const response=await fetch("/api/admin/books",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:book.id,coverUrl})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível atualizar a capa.");
      setCoverlessBooks(current=>current.filter(item=>item.id!==book.id));setBooks(current=>current.map(item=>item.id===book.id?data.book:item));setBookSearchResults(current=>current.map(item=>item.id===book.id?data.book:item));setCoverSearchResults(current=>current.map(item=>item.id===book.id?data.book:item));cancelCoverEdit();setMessage(`Capa de ${data.book.title} adicionada com sucesso.`);
    }catch(error){setMessage(error instanceof Error?error.message:"Não foi possível atualizar a capa.");}finally{setCoverBusyId(null);}
  }
  async function updateRequest(id:string,action:"archive"|"reopen"|"notify"){const response=await fetch("/api/admin/requests",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action})});const data=await response.json();if(!response.ok){setMessage(data.error||"Erro ao atualizar pedido.");return;}if(data.request)setRequests(current=>current.map(item=>item.id===id?{...item,...data.request}:item));if(action==="notify")setMessage(data.notification?.notificationSent?"Notificação reenviada.":data.notification?.reason||"Notificação não entregue.");}
  async function addCategory(formData:FormData){const response=await fetch("/api/admin/categories",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:String(formData.get("name")||""),parentId:String(formData.get("parent_id")||"")||null})});const data=await response.json();if(response.ok)setCategories(current=>[...current,data.category].sort((a,b)=>a.name.localeCompare(b.name)));else setMessage(data.error||"Erro ao criar categoria.");}
  async function removeCategory(id:string){if(!confirm("Excluir esta categoria?"))return;const response=await fetch(`/api/admin/categories?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(response.ok)setCategories(current=>current.filter(item=>item.id!==id));}
  async function generateInvite(){setBusy(true);setMessage("");setInvite(null);try{const response=await fetch("/api/admin/invite-codes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({planType:invitePlan})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível gerar o código.");setInvite(data);setMessage("Código de usuário gerado. Envie o link ao assinante.");}catch(error){setMessage(error instanceof Error?error.message:"Erro ao gerar código.");}finally{setBusy(false);}}
  async function copyInvite(value:string,label:string){try{await navigator.clipboard.writeText(value);setMessage(`${label} copiado.`);}catch{window.prompt(`Copie o ${label.toLowerCase()}:`,value);}}
  async function updateUser(id:string,patch:{approved?:boolean;password?:string}){const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...patch})});const data=await response.json();if(response.ok){setProfiles(current=>current.map(profile=>profile.id===id?data.profile:profile));setMessage(patch.password?"Senha redefinida.":"Usuário atualizado.");}else setMessage(data.error||"Erro ao atualizar usuário.");}
  async function connectDrive(){const response=await fetch("/api/drive/auth-url");const data=await response.json();if(response.ok&&data.url)location.href=data.url;else setMessage(data.error||"Não foi possível conectar o Drive.");}

  const tabs:[Tab,string][]=[["pedidos",`Pedidos (${pendingRequests.length})`],["corrigir",`Corrigir (${correctionCount})`],["editar","Editar livros"],["capas","Editar capas"],["leitura","Leitura"],["categorias","Categorias"],["usuarios","Usuários"],["drive","Google Drive"]];
  return <>
    <div className="tabs">{tabs.map(([key,label])=><button key={key} className={`tab ${tab===key?"active":""}`} onClick={()=>setTab(key)}>{label}</button>)}</div>
    {message&&<div role="status" aria-live="polite" className={`notice ${/sucesso|criado|publicado|atualizado|liberado|reenviada|telegram:/i.test(message)?"success":""}`}>{message}</div>}

    {tab==="editar"&&<div className="admin-grid">
      <section className="card panel"><div className="panel-title"><div><span className="eyebrow">{editing?"EDIÇÃO":"NOVO TÍTULO"}</span><h2>{editing?`Editar ${editing.title}`:"Adicionar livro"}</h2></div>{(editing||requestId)&&<button className="btn ghost small" onClick={resetForm}>Cancelar</button>}</div>
        {requestId&&<div className="notice success">Este cadastro veio de um pedido. Ao publicar, o pedido será marcado como atendido.</div>}
        <form id="book-form" className="stack" action={formData=>saveBook(formData,!editing)}>
          <label className="suggestion-box">Título ou ISBN<input value={draft.title} onChange={event=>{setDraft(current=>({...current,title:event.target.value}));setSelected(null);setMetadataError("");}} placeholder="Digite o título ou ISBN completo" required/>{partialIsbn(draft.title)&&<small>Continue digitando o ISBN completo (10 ou 13 dígitos).</small>}{searching&&<small>Buscando em Google Books, Open Library, editoras e Crossref...</small>}{metadataError&&<small className="metadata-search-error">{metadataError}</small>}{suggestions.length>0&&<div className="suggestions">{suggestions.map(item=><button type="button" className="suggestion" key={item.id} onClick={()=>chooseMetadata(item)}>{item.coverUrl?<img src={item.coverUrl} alt=""/>:<span/>}<span><strong>{item.title}</strong><small>{item.author}{item.year?` • ${item.year}`:""}</small></span></button>)}</div>}</label>
          <label>Autor<input value={draft.author} onChange={event=>setDraft(current=>({...current,author:event.target.value}))} required/></label>
          <label>Idioma<input value={draft.language} onChange={event=>setDraft(current=>({...current,language:event.target.value}))}/></label>
          <label>Sinopse<textarea value={draft.description} onChange={event=>setDraft(current=>({...current,description:event.target.value}))}/></label>
          <label>Categoria<select value={draft.categoryId||suggestedCategory||""} onChange={event=>setDraft(current=>({...current,categoryId:event.target.value}))}><option value="">Sem categoria</option>{categories.map(category=><option value={category.id} key={category.id}>{category.name}</option>)}</select></label>
          <label>URL da capa (opcional)<input value={draft.coverUrl} onChange={event=>setDraft(current=>({...current,coverUrl:event.target.value}))}/></label>
          <label>Ou envie a capa do dispositivo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>setCoverFile(event.target.files?.[0]||null)}/><small>{coverFile?`Capa selecionada: ${coverFile.name}`:"Você pode cadastrar o livro sem capa e adicioná-la depois ao editar."}</small></label>
          <div className="file-pair"><label><strong>Arquivo EPUB</strong><span>{editing?"Opcional — envie apenas para substituir":"Obrigatório"}</span><input type="file" accept=".epub,application/epub+zip" onChange={event=>{const file=event.target.files?.[0]||null;setEpubFile(file);if(file)void absorbFileMetadata(file,"epub");}}/>{epubFile&&<small>{driveFileName(draft.title,epubFile.name)}</small>}</label><label><strong>Arquivo PDF</strong><span>{editing?"Opcional — envie apenas para substituir":"Obrigatório"}</span><input type="file" accept=".pdf,application/pdf" onChange={event=>{const file=event.target.files?.[0]||null;setPdfFile(file);if(file)void absorbFileMetadata(file,"pdf");}}/>{pdfFile&&<small>{driveFileName(draft.title,pdfFile.name)}</small>}</label></div>
          {fileMetadataNote&&<div className="file-metadata-note">{fileMetadataNote}</div>}
          {busy&&<div className="upload-progress"><span style={{width:`${progress}%`}}/></div>}
          <button className="btn" disabled={busy||telegramBusyId!==null}>{busy?(progress?`${editing?"Salvando alterações":"Enviando livro"} • ${progress}%`:editing?"Salvando alterações...":"Enviando livro..."):editing?"Salvar alterações":"Enviar livro"}</button>
          <small className="telegram-publish-hint">{editing?"As alterações são salvas no catálogo. EPUB e PDF só são substituídos se você enviar novos arquivos.":"Um único envio publica o livro no site e encaminha EPUB + PDF aos canais Oficial e Reserva do Telegram."}</small>
        </form>
      </section>
      <section className="card panel admin-library-panel"><div className="panel-title"><div><span className="eyebrow">EDIÇÃO MANUAL</span><h2>Pesquisar e editar livros</h2><p>Digite pelo menos 4 letras do título ou autor para localizar qualquer livro do acervo.</p></div><span className="count-badge">{bookSearchReady?shownBooks.length:books.length}</span></div>
        <div className="admin-book-search"><input type="search" value={bookSearch} onChange={event=>setBookSearch(event.target.value)} placeholder="Digite 4 letras do título ou autor..." aria-label="Pesquisar qualquer livro do acervo"/>{bookSearch&&<button type="button" className="btn ghost small" onClick={()=>setBookSearch("")}>Limpar</button>}</div>
        <p className="admin-list-hint">{bookSearch&& !bookSearchReady?`Digite mais ${4-normalizedBookSearch.length} ${4-normalizedBookSearch.length===1?"letra":"letras"} para pesquisar em todo o acervo.`:bookSearchBusy?"Pesquisando...":bookSearchError?`Erro na pesquisa: ${bookSearchError}`:bookSearchReady?`${shownBooks.length} ${shownBooks.length===1?"resultado encontrado":"resultados encontrados"} no acervo`:`Mostrando ${Math.min(8,books.length)} livros adicionados recentemente`}</p>
        <div className="admin-book-list">{shownBooks.length?shownBooks.map(book=><article className="admin-book" key={book.id}>{book.cover_url?<img src={book.cover_url} alt=""/>:<span className="mini-cover"/>}<div><strong>{book.title}</strong><small>{book.author} • {book.categories?.name||(book.category_id?"Categoria cadastrada":"Sem categoria")} • {book.published?"Publicado":"Oculto"}</small><small>URL: /livro/{book.slug}</small></div><div className="row wrap"><button className="btn ghost small" onClick={()=>editBook(book)}>Editar</button><button className="btn telegram-mini small" disabled={telegramBusyId===book.id} onClick={()=>void publishExisting(book)}>{telegramBusyId===book.id?"Reenviando...":"Reenviar Telegram"}</button><button className="btn danger small" onClick={()=>removeBook(book.id)}>Excluir</button></div></article>):<div className="empty-state admin-search-empty"><h3>Nenhum livro encontrado</h3><p>Confira a escrita ou tente somente as primeiras letras do título ou autor.</p></div>}</div></section>
    </div>}

    {tab==="capas"&&<section className="card panel"><div className="panel-title"><div><span className="eyebrow">CAPAS FALTANTES</span><h2>Editar capas</h2><p>Mostrando apenas os livros que ainda estão sem capa. Você pode adicionar uma capa, editar o livro ou excluí-lo.</p></div><span className="count-badge">{coverlessBooks.length}</span></div>
      <div className="admin-book-search"><input type="search" value={coverSearch} onChange={event=>setCoverSearch(event.target.value)} placeholder="Pesquisar por título, autor ou categoria..." aria-label="Pesquisar livros sem capa"/>{coverSearch&&<button type="button" className="btn ghost small" onClick={()=>setCoverSearch("")}>Limpar</button>}</div>
      <p className="admin-list-hint">{coverSearch&&!coverSearchReady?`Digite mais ${4-normalizedCoverSearch.length} ${4-normalizedCoverSearch.length===1?"letra":"letras"} para pesquisar em todo o acervo.`:coverSearchBusy?"Pesquisando...":coverSearchReady?`${shownCoverlessBooks.length} ${shownCoverlessBooks.length===1?"resultado encontrado":"resultados encontrados"} no acervo`:`Mostrando ${Math.min(12,coverlessBooks.length)} de ${coverlessBooks.length} livros sem capa`}</p>
      <div className="admin-book-list">{shownCoverlessBooks.length?shownCoverlessBooks.map(book=><article className="admin-book" key={book.id}>{book.cover_url?<img src={book.cover_url} alt=""/>:<span className="mini-cover"/>}<div><strong>{book.title}</strong><small>{book.author||"Autor não informado"} • {book.categories?.name||"Sem categoria"} • {book.published?"Publicado":"Oculto"}</small><small>URL: /livro/{book.slug}</small></div><div className="row wrap"><button className="btn small" onClick={()=>editCover(book)}>{book.cover_url?"Alterar capa":"Adicionar capa"}</button><button className="btn ghost small" onClick={()=>editBook(book)}>Editar livro</button><button className="btn danger small" onClick={()=>void removeBook(book.id)}>Excluir</button></div>{coverEditingId===book.id&&<div className="stack" style={{gridColumn:"1 / -1",width:"100%"}}><label>URL da capa<input value={coverDraftUrl} onChange={event=>setCoverDraftUrl(event.target.value)} placeholder="https://..."/></label><label>Ou envie uma imagem do dispositivo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>setCoverImage(event.target.files?.[0]||null)}/><small>{coverImage?`Imagem selecionada: ${coverImage.name}`:"JPG, PNG ou WEBP, até 5 MB."}</small></label><div className="row wrap"><button className="btn small" disabled={coverBusyId===book.id} onClick={()=>void saveCover(book)}>{coverBusyId===book.id?"Salvando...":"Salvar capa"}</button><button className="btn ghost small" disabled={coverBusyId===book.id} onClick={cancelCoverEdit}>Cancelar</button></div></div>}</article>):<div className="empty-state admin-search-empty"><h3>{coverSearchReady?"Nenhum livro encontrado":coverlessBooks.length?"Nenhum livro encontrado":"Nenhum livro sem capa"}</h3><p>{coverSearchReady?"Tente pesquisar por outro título ou autor.":coverlessBooks.length?"Digite pelo menos 4 letras para buscar em todo o acervo.":"Todos os livros cadastrados já possuem capa."}</p></div>}</div>
    </section>}

    {tab==="corrigir"&&<CorrectionDashboard initialBooks={initialCorrectionBooks} initialTotal={initialCorrectionCount} onCountChange={setCorrectionCount}/>}

    {tab==="leitura"&&<ReadingDashboard/>}

    {tab==="pedidos"&&<section className="card panel"><div className="panel-title"><div><span className="eyebrow">SITE + TELEGRAM</span><h2>Pedidos de livros</h2><p>Todos os pedidos feitos pelo formulário do site ou pelo bot aparecem juntos aqui.</p></div><span className="count-badge">{pendingRequests.length}</span></div><div className="request-list">{pendingRequests.length?pendingRequests.map(item=><article className="request-card" key={item.id}><div><span className="request-date">{date(item.created_at)}</span><h3>{item.title}</h3><p>{item.author} • {languageName(item.language)}</p><small>{item.requester_name||item.requester_email||"Assinante"}{item.telegram_username?` • @${item.telegram_username}`:""}</small></div><div className="row wrap"><button className="btn small" onClick={()=>useRequest(item)}>Cadastrar este livro</button><button className="btn ghost small" onClick={()=>updateRequest(item.id,"archive")}>Arquivar</button></div></article>):<div className="empty-state"><h3>Nenhum pedido pendente</h3><p>Novos pedidos do site e do Telegram aparecerão aqui.</p></div>}</div>{completedRequests.length>0&&<details className="request-history"><summary>Ver pedidos concluídos e arquivados ({completedRequests.length})</summary>{completedRequests.map(item=><div className="table-row" key={item.id}><div><strong>{item.title}</strong><small>{item.status==="published"?"Publicado":"Arquivado"}</small></div><div className="row">{item.status==="published"&&!item.notified_at&&item.telegram_username&&<button className="btn small" onClick={()=>updateRequest(item.id,"notify")}>Reenviar aviso</button>}<button className="btn ghost small" onClick={()=>updateRequest(item.id,"reopen")}>Reabrir</button></div></div>)}</details>}</section>}

    {tab==="categorias"&&<section className="card panel"><div className="panel-title"><div><span className="eyebrow">ORGANIZAÇÃO</span><h2>Categorias e subcategorias</h2><p>Crie uma categoria principal ou escolha abaixo a categoria à qual a nova subcategoria pertence.</p></div></div><form className="category-create-form" action={addCategory}><label>Nome<input name="name" placeholder="Ex.: Romance contemporâneo" required/></label><label>Categoria principal<select name="parent_id"><option value="">Nenhuma — criar categoria principal</option>{categories.filter(item=>!item.parent_id).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><button className="btn">Criar</button></form><div className="category-admin-grid">{categories.filter(item=>!item.parent_id).map(parent=><article className="category-admin-card" key={parent.id}><div className="category-admin-head"><strong>{parent.name}</strong><button className="btn danger small" onClick={()=>removeCategory(parent.id)}>Excluir</button></div><div className="subcategory-list">{categories.filter(item=>item.parent_id===parent.id).map(child=><div className="subcategory-row" key={child.id}><span>{child.name}</span><button className="btn ghost small" onClick={()=>removeCategory(child.id)}>Excluir</button></div>)}{!categories.some(item=>item.parent_id===parent.id)&&<small>Nenhuma subcategoria.</small>}</div></article>)}</div></section>}

    {tab==="usuarios"&&<div className="admin-grid"><section className="card panel"><span className="eyebrow">NOVO ASSINANTE</span><h2>Gerar código de usuário</h2><p className="muted">Depois de confirmar o pagamento, gere um código e envie o link de criação de conta ao assinante. Ele escolherá apenas nome de usuário e senha.</p><div className="stack"><label>Tipo de acesso<select value={invitePlan} onChange={event=>setInvitePlan(event.target.value as "monthly"|"lifetime")}><option value="monthly">Mensal · 30 dias</option><option value="lifetime">Vitalício</option></select></label><button type="button" className="btn" disabled={busy} onClick={()=>void generateInvite()}>{busy?"Gerando...":"Gerar código de usuário"}</button>{invite&&<div className="notice success"><strong>Código pronto</strong><p>O link já leva o código preenchido. Ele é válido até {date(invite.expiresAt)} e só pode ser usado uma vez.</p><div className="stack"><label>Código<input value={invite.code} readOnly onFocus={event=>event.currentTarget.select()}/></label><label>Link de criação<input value={invite.link} readOnly onFocus={event=>event.currentTarget.select()}/></label><div className="row wrap"><button type="button" className="btn small" onClick={()=>void copyInvite(invite.link,"Link")}>Copiar link</button><button type="button" className="btn ghost small" onClick={()=>void copyInvite(invite.code,"Código")}>Copiar código</button></div></div></div>}</div><Link className="text-link" href="/admin/assinaturas">Gerenciar vencimentos e pagamentos →</Link></section><section className="card panel"><div className="panel-title"><div><span className="eyebrow">ACESSOS</span><h2>Usuários</h2></div><span className="count-badge">{profiles.length}</span></div><div className="table-list">{profiles.map(profile=><div className="table-row user-row" key={profile.id}><div><strong>{profile.username?`@${profile.username}`:profile.full_name||"Usuário"}</strong><small>{profile.full_name&&profile.full_name!==profile.username?`${profile.full_name} • `:""}{profile.role} • {profile.approved?"ativo":"bloqueado"}</small></div><div className="row wrap"><button className="btn ghost small" onClick={()=>{const password=prompt("Digite a nova senha (mínimo 8 caracteres):");if(password)void updateUser(profile.id,{password});}}>Redefinir senha</button><button className="btn small" onClick={()=>void updateUser(profile.id,{approved:!profile.approved})}>{profile.approved?"Bloquear":"Ativar"}</button></div></div>)}</div></section></div>}

    {tab==="drive"&&<section className="card panel drive-panel"><span className="eyebrow">ARMAZENAMENTO</span><h2>Google Drive</h2><div className="drive-status"><span className={`status-dot ${drive.connected?"on":""}`}/><div><strong>{drive.connected?"Drive conectado":"Drive desconectado"}</strong>{drive.accountEmail&&<small>{drive.accountEmail}</small>}</div></div><p className="muted">Livros, PDFs, EPUBs, capas e versões Kindle são enviados para suas áreas próprias no Google Drive.</p><div className="row"><button className="btn" onClick={connectDrive}>{drive.connected?"Reconectar":"Conectar Google Drive"}</button><button className="btn ghost" onClick={()=>void refreshDrive()}>Verificar</button></div></section>}
  </>;
}
